vich_uploader:
    db_driver: orm
    mappings:
        game_backdrop:
            uri_prefix: /img/backdrops
            upload_destination: '%kernel.project_dir%/public/img/backdrops'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        game_poster:
            uri_prefix: /img/posters/games
            upload_destination: '%kernel.project_dir%/public/img/posters/games'
            namer: Vich\UploaderBundle\Naming\UniqidNamer